version: '3.4'

services:
  pokerengine:
    image: pokerengine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8111:8111
